name:           The Final Countdown
nickname:       jQuery.countdown
plugin_version: 2.1.0
baseurl:        http://hilios.github.io/jQuery.countdown
highlight:      true
markdown:       redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
